version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Script para instalar Apache y PHP
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_apache.sh  # Script para reiniciar Apache después de la instalación
      timeout: 300
      runas: root
